language: node_js
node_js:
- '8'
env:
- AETERNITY_EPOCH_API_URL='//republica.aepps.com/'
- NAME_LOOKUP_MIDDLEWARE_URL='//republica-pos.aepps.com/rest/name/'
- SHOW_MARKET_STATS=false
- SHOW_NETWORK_STATS=false
install:
- npm install
script:
- npm run build
deploy:
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/explorer.aepps.com/
  on:
    branch: explorer
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/stage-explorer.aepps.com/
  on:
    branch: stage
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/integration-explorer.aepps.com/
  on:
    branch: integration-explorer
- provider: script
  skip_cleanup: true
  script: rsync -r --delete-after -v $TRAVIS_BUILD_DIR/dist/* deploy@139.59.142.164:/var/www/html/republica-explorer.aepps.com/
  on:
    branch: republica-pos
before_install:
- openssl aes-256-cbc -K $encrypted_90a9ca14a0f9_key -iv $encrypted_90a9ca14a0f9_iv
  -in deploy.enc -out deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy
- ssh-add deploy
- mkdir -p ~/.ssh
- echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
